### ISSUE TITLE
你好，请问一下starneto_ros_msgs这个库要从哪里获得？Hello, where can I get starneto_ros_msgs library？

### ISSUE THREAD

**Issue by wangxb-code** [HRex39/Newton-M2-Ros-Driver#1]

**Comment by HRex39** [comment]
您好，

具体是什么样的报错信息呢？

ros_msgs在repo中已经写好了
您需要先建立一个catkin workspace然后再将repo clone进其中

**Comment by wangxb-code** [comment]
非常感谢您的回答！我将您的驱动包放在catkin_ws/src/路径下，具体路径是catkin_ws/src/Newton-M2-Ros-Driver,在进行catkin_make编译的时候出现这个错误：
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "starneto_ros_msgs"
  with any of the following names:

    starneto_ros_msgsConfig.cmake
    starneto_ros_msgs-config.cmake

 Add the installation prefix of "starneto_ros_msgs" to CMAKE_PREFIX_PATH or
  set "starneto_ros_msgs_DIR" to a directory containing one of the above
  files.  If "starneto_ros_msgs" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  Newton-M2-Ros-Driver/starneto/CMakeLists.txt:13 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/nvidia/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/nvidia/catkin_ws/build/CMakeFiles/CMakeError.log".
Makefile:1650: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed
这里编译不成功，提示的是找不到starneto_ros_msgs这个包，另外您说的repo是在哪里，我没有找到。抱歉我刚接触IMU数据获取这方面，是个新手。

**Comment by HRex39** [comment]
有没有尝试过用catkin build？

如果采用catkin_make应当首先编译starneto_ros_msgs的包，因为他会在之后的其他编译中使用到，当starneto没有先进行编译时，就会带来这样的报错。

总之，还是比较建议采用catkin build进行项目的构建，因为他对于每个包都是单独编译的。如我的现在这个repository有三个包，它会将每个包单独编译互不影响。

**Comment by HRex39** [comment]
如果不想使用catkin build，最简单的方法就是先把starneto包移出，先进行starneto_ros_msgs的编译，再把starneto的包放回去
