### ISSUE TITLE
catkin_build错误

### ISSUE THREAD

**Issue by wangxb-code** [HRex39/Newton-M2-Ros-Driver#2]
你好，我在进行catkin_build编译的时候，提示错误信息：
Errors     << starneto_mems:make /home/nvidia/catkin_ws1/logs/starneto_mems/build.make.000.log
/home/nvidia/catkin_ws1/src/Newton-M2-Ros-Driver/starneto/src/main.cpp:19:10: fatal error: slcurses.h: No such file or directory
 #include <slcurses.h>
          ^~~~~~~~~~~~
compilation terminated.
提示没有slcurses.h文件，我找了一下好像确实没有，请问这个文件是需要从其他地方下载吗？

**Comment by HRex39** [comment]
好像把这行删除后就没有这个问题了？  
似乎是我误加的一个include？  
感谢您的反馈
