### ISSUE TITLE
自定义消息类型中的Header如何输出？

### ISSUE THREAD

**Issue by wangxb-code** [HRex39/Newton-M2-Ros-Driver#3]
你好，非常感谢您写的驱动，我已经获取到了相关的GTIMU数据，通过订阅/GTIMU话题的方式完成的，订阅后进行终端输出，但当我想输出header.stamp的时候报错了，错误如下：
。。。
。。。
TypeError: %d format: a number is required, not Time
我以为这个时间是%d类型的，看了代码，发现header.stamp是ros的时间ros::Time::now()，我想请问一下这个数据是什么类型的，该怎么输出，还有就是您自定义的消息类型中Header是怎么定义的，就是在main文件中定义成header.stamp=...... 和header.frame_id=......吗？

**Comment by HRex39** [comment]
自定义消息格式见[这里](https://github.com/HRex39/Newton-M2-Ros-Driver/tree/main/starneto_ros_msgs/msg)
Header的stamp详细见ros官方文档。

**Comment by HRex39** [comment]
CSDN中有几个简单范例可以参考
[点击](https://blog.csdn.net/qq_18676517/article/details/109270525)

**Comment by wangxb-code** [comment]
十分感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月12日(星期四) 下午5:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HRex39/Newton-M2-Ros-Driver] 自定义消息类型中的Header如何输出？ (Issue #3)





 
CSDN中有几个简单范例可以参考
 点击
