### ISSUE TITLE
IMU标定

### ISSUE THREAD

**Issue by wangxb-code** [HRex39/Newton-M2-Ros-Driver#4]
请问一下，星网宇达IMU标定内参的时候需要四元数吗？

**Comment by HRex39** [comment]
这个问题具体可以在标定的repo询问。

**Comment by wangxb-code** [comment]
好的





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月12日(星期四) 晚上8:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HRex39/Newton-M2-Ros-Driver] IMU标定 (Issue #4)





 
这个问题具体可以在标定的repo询问。
