### ISSUE TITLE
运行节点报错

### ISSUE THREAD

**Issue by wangxb-code** [HRex39/Newton-M2-Ros-Driver#7]
[ERROR] [1655196459.154834967]: serial port: /dev/ttyACM0 init failed.
[ERROR] [1655196459.164974422]: serial port: /dev/ttyACM0 init failed.
[ERROR] [1655196459.174558325]: serial port: /dev/ttyACM0 init failed.
[ERROR] [1655196459.184834654]: serial port: /dev/ttyACM0 init failed.
[ERROR] [1655196459.194556284]: serial port: /dev/ttyACM0 init failed.
[ERROR] [1655196459.204525420]: serial port: /dev/ttyACM0 init failed.
[ERROR] [1655196459.214497535]: serial port: /dev/ttyACM0 init failed.
[ERROR] [1655196459.224579238]: serial port: /dev/ttyACM0 init failed.
[ERROR] [1655196459.235219477]: serial port: /dev/ttyACM0 init failed.

请问一下，我运行节点之后为什么报这个错，编译通过了，使用cutecom也正常获取数据了

**Comment by HRex39** [comment]
需要看一下你的串口端口是哪一个 详情可以在config的yaml文件中更改

**Comment by HRex39** [comment]
同时，你的串口/USB端口能被读取么？不能的话需要赋权。您是金龙的员工么？
